-
  version: 0.1.1.{build}
  branches:
    only:
      - master
  skip_tags: true
  image: Visual Studio 2015
  assembly_info:
    patch: true
    file: src\NPolyglot.Core\Properties\AssemblyInfo.cs
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}-alpha"
  nuget:
    account_feed: true
    project_feed: false
    disable_publish_on_pr: true
  platform: Any CPU
  configuration: Release
  before_build:
    - nuget restore
  after_build:
    - nuget pack build\Npolyglot.Core.nuspec -properties version=0.1.1-alpha;configuration=%CONFIGURATION%
    - nuget pack build\Npolyglot.LanguageDesign.nuspec -properties version=0.1.1-alpha;configuration=%CONFIGURATION%
  artifacts:
    - path: '**\*.nupkg'
      type: NuGetPackage
-
  version: 0.1.1.{build}
  branches:
    only:
      - develop
  skip_tags: true
  image: Visual Studio 2015
  assembly_info:
    patch: true
    file: src\NPolyglot.Core\Properties\AssemblyInfo.cs
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}-dev"
  nuget:
    account_feed: true
    project_feed: false
    disable_publish_on_pr: true
  platform: Any CPU
  configuration: Debug
  before_build:
    - nuget restore
  after_build:
    - nuget pack build\Npolyglot.Core.nuspec -properties version=0.1.1-dev;configuration=%CONFIGURATION%
    - nuget pack build\Npolyglot.LanguageDesign.nuspec -properties version=0.1.1-dev;configuration=%CONFIGURATION%
  artifacts:
    - path: '**\*.nupkg'
      type: NuGetPackage
