-
  version: 0.1.0
  branches:
    only:
      - master
  skip_tags: true
  image: Visual Studio 2015
  assembly_info:
    patch: true
    file: src\NPolyglot.Core\Properties\AssemblyInfo.cs
    assembly_version: "{version}.0"
    assembly_file_version: "{version}.0"
    assembly_informational_version: "{version}-alpha"
  nuget:
    account_feed: true
    project_feed: false
    disable_publish_on_pr: true
  platform: Any CPU
  configuration: Release
  build:
    publish_nuget: true
  artifacts:
    - path: build\*.nupkg
      type: NuGetPackage
-
  version: 0.1.1
  branches:
    only:
      - master
  skip_tags: true
  image: Visual Studio 2015
  assembly_info:
    patch: true
    file: src\NPolyglot.Core\Properties\AssemblyInfo.cs
    assembly_version: "{version}.1"
    assembly_file_version: "{version}.1"
    assembly_informational_version: "{version}-dev"
  nuget:
    account_feed: true
    project_feed: false
    disable_publish_on_pr: true
  platform: Any CPU
  configuration: Release
  build:
    publish_nuget: true
  artifacts:
    - path: build\*.nupkg
      type: NuGetPackage
